version: 2.1

orbs:
  slack: circleci/slack@4.9.3

parameters:
  build:
    type: boolean
    default: false

  android:
    type: boolean
    default: false

  build_prod:
    type: boolean
    default: false

  android_prod:
    type: boolean
    default: false

jobs:
  android-debug-build:
    working_directory: ~/repo

    docker:
      - image: cimg/android:2022.09.2-node
    # resource_class: medium+ # fails on medium+

    steps:
      - checkout:
          path: ~/repo

      # - run:
      #     name: Building Android build
      #     command: echo "building"

      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: build debug version
          command: ./gradlew assembleDebug
          working_directory: android

      - store_artifacts:
          path: android/app/build/outputs/apk/debug

      - run:
          name: Upload to Slack
          command: |
            export GIT_COMMIT_DESC=$(git log --format=oneline -n 1 | sed -E 's/^[^ ]+ (.*)$/\1/g')
            curl -F file=@android/app/build/outputs/apk/debug/app-debug.apk -F channels=$SLACK_CHANNEL -F token=xoxb-5183023887109-5257594118949-1r3L1pNzOscdggSwArpBnhbq -F title="${CIRCLE_PROJECT_REPONAME} | branch -> ${CIRCLE_BRANCH} | commit -> ${GIT_COMMIT_DESC}"  https://slack.com/api/files.upload

      - slack/upload-file:
          channel: C055D0W6885 # Replace with your Slack channel name
          file: android/app/build/outputs/apk/debug/app-debug.apk # Replace with the path to your generated APK file
          filetype: apk

      - slack/notify:
          event: fail
          template: basic_fail_1

      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  android-build:
    when:
      or:
        - << pipeline.parameters.build >>
        - << pipeline.parameters.android >>
    jobs:
      - android-debug-build:
          context: slack-secrets
