version: 2.1

parameters:
  build:
    type: boolean
    default: false

  android:
    type: boolean
    default: false

  build_prod:
    type: boolean
    default: false

  android_prod:
    type: boolean
    default: false

jobs:
  android-debug-build:
    working_directory: ~/repo

    docker:
      - image: cimg/android:2022.09.2-node
    # resource_class: medium+ # fails on medium+

    steps:
      - checkout:
          path: ~/repo

      # - run:
      #     name: Building Android build
      #     command: echo "building"

      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: build debug version
          command: ./gradlew assembleDebug
          working_directory: android

      - store_artifacts:
          path: android/app/build/outputs/apk/debug

      - run:
          name: Upload to Slack
          command: |
            export GIT_COMMIT_DESC=$(git log --format=oneline -n 1 | sed -E 's/^[^ ]+ (.*)$/\1/g')
            curl -F file=@app/build/outputs/apk/debug/app-debug.apk -F channels=$SLACK_CHANNEL -F token=$SLACK_API_TOKEN -F title="${CIRCLE_PROJECT_REPONAME} | branch -> ${CIRCLE_BRANCH} | commit -> ${GIT_COMMIT_DESC}"  https://slack.com/api/files.upload

workflows:
  android-build:
    when:
      or:
        - << pipeline.parameters.build >>
        - << pipeline.parameters.android >>
    jobs:
      - android-debug-build
