version: 2.1

orbs:
  slack: circleci/slack@4.9.3

parameters:
  build:
    type: boolean
    default: false

  android:
    type: boolean
    default: false

  build_prod:
    type: boolean
    default: false

  android_prod:
    type: boolean
    default: false

jobs:
  android-debug-build:
    working_directory: ~/repo

    docker:
      - image: cimg/android:2022.09.2-node
    # resource_class: medium+ # fails on medium+

    steps:
      - checkout:
          path: ~/repo

      # - run:
      #     name: Building Android build
      #     command: echo "building"

      - run:
          name: Install Dependencies
          command: yarn install

      - run:
          name: build debug version
          command: ./gradlew assembleDebug
          working_directory: android

      - store_artifacts:
          path: android/app/build/outputs/apk/debug

      - run:
          name: Upload to Slack
          command: |
            export GIT_COMMIT_DESC=$(git log --format=oneline -n 1 | sed -E 's/^[^ ]+ (.*)$/\1/g')
            curl -F file=@android/app/build/outputs/apk/debug/app-debug.apk -F channels=$SLACK_CHANNEL -F token=$SLACK_ACCESS_TOKEN -F title="${CIRCLE_PROJECT_REPONAME} | branch -> ${CIRCLE_BRANCH} | commit -> ${GIT_COMMIT_DESC}"  https://slack.com/api/files.upload

      # - slack/upload-file:
      #     channel: C055D0W6885 # Replace with your Slack channel name
      #     file: android/app/build/outputs/apk/debug/app-debug.apk # Replace with the path to your generated APK file
      #     filetype: apk

      - slack/notify:
          event: fail
          template: basic_fail_1

      - slack/notify:
          event: pass
          custom: |
            {
              "attatchments": [
                {
                  "blocks": [
                    {
                      "type": "header",
                      "text": {
                        "type": "plain_text",
                        "text": "Build Successful! :tada:",
                        "emoji": true
                      }
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Branch*: \n$CIRCLE_BRANCH"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Commit*: \n${CIRCLE_SHA1:0:10}"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Job*: \n$CIRCLE_JOB ($CIRCLE_BUILD_NUM)"
                        }
                      ],
                      "accessory": {
                        "type": "image",
                        "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                        "alt_text": "CircleCI logo"
                      }
                    },
                    {
                      "type": "actions",
                      "elements": [
                        {
                          "type": "button",
                          "action_id": "success_tagged_deploy_view",
                          "text": {
                            "type": "plain_text",
                            "text": "View Job"
                          },
                          "url": "$CIRCLE_BUILD_URL"
                        }
                      ]
                    }
                  ]
                }
              ],
            }


workflows:
  android-build:
    when:
      or:
        - << pipeline.parameters.build >>
        - << pipeline.parameters.android >>
    jobs:
      - android-debug-build:
          context: slack-secrets
